name: website tests
on:
  push:
  pull_request:

jobs:
  build_release:
    name: build release
    runs-on: ubuntu-16.04
    timeout-minutes: 50
    steps:
    - uses: actions/checkout@v2
    - name: Push docker image
      run: |
        docker build -t grekiki/website .
        docker login -u grekiki -p ${{secrets.DOCKER_PASSWORD}}
        docker push grekiki/website

  unit_tests:
    name: unit tests
    runs-on: ubuntu-16.04
    timeout-minutes: 50
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: coverage run --append -m unittest discover tests